// try,catch and finally
try{
    let c = undefined ; 
    console.log("value of undefined :",c[0]);
}catch{
    console.log("excuted when error in try section:");
}finally{
    console.log("finally always excute");
}
